name: Build Vue
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: xRealNeon/VuePagesAction@bb1a496e439e523025f6f37a2bd37ce8a8835c04
        with:
          username: "RPMTW"
          reponame: "RPMTW-Website"
          token: ${{ secrets.GITHUB_TOKEN }}
          gitmsg: Update Website
          cname: www.rpmtw.com
          gitname: Website-BOT
          useyarn: true
