name: Build Vue
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'RPMTW'
        reponame: 'RPMTW-Website'
        token: ${{ secrets.GITHUB_TOKEN }}