name: Build Vue
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: xRealNeon/VuePagesAction@3415ebf6420a1d77fb8ff4e60c8624c30edd48ef
        with:
          username: "RPMTW"
          reponame: "RPMTW-Website"
          token: ${{ secrets.GITHUB_TOKEN }}
          gitmsg: Update Website
          cname: www.rpmtw.com
          gitname: Website-BOT
          useyarn: true
