name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: cp "${{ github.workspace }}/docs/index.html" "${{ github.workspace }}/404.html"
    - run: rm -rf ${{ github.workspace }}/docs*
    - run: npm install
    - run: npm run build
    - run: cp -r "${{ github.workspace }}/404.html" "${{ github.workspace }}/docs/404.html"
    - run: echo www.rpmtw.ga >> "${{ github.workspace }}/docs/CNAME"

    - name: "Update File"
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'actions@users.noreply.github.com'
        @"
        protocol=https
        host=github.com
        username=github-actions[bot]
        password=${{ secrets.GITHUB_TOKEN }}
        "@ > .\1.txt
        gc 1.txt|git credential-manager  store
        ri .\1.txt -Force
        git add ${{ github.workspace }}/docs
        git commit -m "Update Website"
        git push origin HEAD:${{ github.ref }}
      shell: pwsh           